JDP200901-11 Order entity implementation
piotr-grosicki/project-jdp-2009-01 pull request #13
Opened 2020-09-24 20:45 UTC by hubertb98

- Wprowadziłem implementację klasy order,
- Wprowadziłem relację między klasami z klasą Order,
- Poprawiłem obiekt w klasie CartController,
- gradlew build nie przechodzi ze względu na UserDao (powód: "uses unchecked or unsafe operations.")

2020-09-24 21:15 UTC, piotr-grosicki requested changes
Projekt sie nie buduje. Aby moc zmergowac projekt musi sie budowac

2020-09-24 22:13 UTC, hubertb98 commented
- Poprawione błędy
- Poprawione relacje między klasami,
- Napisane klasy potrzebne do wprowadzenia relacji

2020-09-25 07:07 UTC, piotr-grosicki requested changes
Konflikt na klasie product, mozesz juz uzyc implementacji dostarczonej w zadaniu z ProductEntity

2020-09-25 07:32 UTC, hubertb98 commented
Po użyciu implementacji z ProductEntity projekt mi się nie buduję, ponieważ w ProductEntity nie ma wprowadzonych relacji

2020-09-25 07:56 UTC, piotr-grosicki commented
> Po użyciu implementacji z ProductEntity projekt mi się nie buduję, ponieważ w ProductEntity nie ma wprowadzonych relacji

to trzeba takie dodac

2020-09-25 10:33 UTC, piotr-grosicki requested changes

2020-09-25 10:33 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    @OneToMany(
raczej many to many :)

2020-09-29 09:05 UTC, piotr-grosicki approved these changes

2020-09-29 09:05 UTC, piotr-grosicki commented
konflikt z `CartController`

2020-09-29 09:06 UTC, piotr-grosicki requested changes
Konflikt

2020-09-30 07:17 UTC, piotr-grosicki approved these changes

2020-09-30 07:18 UTC, merged