Relacja pomiędzy encjami PRODUCT i ORDER
piotr-grosicki/project-jdp-2009-01 pull request #16
Opened 2020-09-26 08:09 UTC by pablodlugi

Stworzyłem relację pomiędzy encjami PRODUCT i ORDER.
Encja ORDER wciąż potrzebuje implementacji (atrybutów).

2020-09-28 07:22 UTC, piotr-grosicki requested changes

2020-09-28 07:22 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    @Column(name = "ORDER_ID", unique = true)
`id` z zasady jest unique, nie trzbea dopisywac

2020-09-28 07:22 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @Column(name = "PRODUCT_ID", unique = true)
`id` z zasady jest unique, nie trzbea dopisywac

2020-09-28 21:07 UTC, hubertb98 approved these changes

2020-09-28 21:57 UTC, draztel reviewed
Moim zdaniem relacja powinna być ORDER 1 : N PRODUCT, polega to na tym, że w jednym zamówieniu jest kilka produktów. może to wywołać konflikty w przyszłości.

2020-09-28 22:25 UTC, hubertb98 commented
> Moim zdaniem relacja powinna być ORDER 1 : N PRODUCT, polega to na tym, że w jednym zamówieniu jest kilka produktów. może to wywołać konflikty w przyszłości.

Ten sam produkt może być w kilku zamówieniach i zamówienie może być przypisane do kilku produktów z tego co rozumiem. Piotr Grosicki wspomniał, że tak ma być a ja tak to rozumiem. ;)

2020-09-28 23:12 UTC, draztel commented
> > Moim zdaniem relacja powinna być ORDER 1 : N PRODUCT, polega to na tym, że w jednym zamówieniu jest kilka produktów. może to wywołać konflikty w przyszłości.
> 
> Ten sam produkt może być w kilku zamówieniach i zamówienie może być przypisane do kilku produktów z tego co rozumiem. Piotr Grosicki wspomniał, że tak ma być a ja tak to rozumiem. ;)

no musiałem to sobie teraz na karteczce rozpisać, rzeczywiście tak jest jak mówisz 👍

2020-09-30 07:18 UTC, piotr-grosicki requested changes
konflikty

2020-09-30 12:50 UTC, sobek21 approved these changes

2020-09-30 19:40 UTC, piotr-grosicki approved these changes

2020-09-30 19:40 UTC, merged