Testy dla encji Cart
piotr-grosicki/project-jdp-2009-01 pull request #18
Opened 2020-09-29 21:31 UTC by pablodlugi

Napisałem testy dla Encji Cart. Przetestowałem również relacje z encjami User i Product. Nie testowałem operacji do których nie jest przeznaczona encja Cart.

2020-09-30 07:20 UTC, piotr-grosicki requested changes

2020-09-30 07:20 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/enity/test/CartEntityTest.java
> +        Assert.assertNotEquals(0, id);
warto by sprawdzic czy ten id jest taki sam jak id cartu a nie inny od 0 ;)

2020-09-30 07:20 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/enity/test/CartEntityTest.java
> +public class CartEntityTest {
brakuje testow na delete, szczegolnie takich sprawdzajacych czy po usunieciu cartu nie usunie sie user, produkty

2020-09-30 12:50 UTC, sobek21 approved these changes

2020-09-30 13:04 UTC, draztel approved these changes

2020-09-30 19:41 UTC, piotr-grosicki requested changes
w komentarzach rzeczy do poprawy

2020-10-03 17:23 UTC, piotr-grosicki approved these changes

2020-10-03 17:23 UTC, merged