task - JDP200901-4 OrderController
piotr-grosicki/project-jdp-2009-01 pull request #2
Opened 2020-09-16 21:07 UTC by hubertb98

Controller powinien:
- Po wywołaniu polecenia GET zwrócić pusty obiekt lub listę obiektów,
- Przy pobieraniu jednego zamówienia trzeba podać orderId,
- Przy dodaniu i update'owaniu zamówień trzeba podać obiekt w formacie JSON

2020-09-17 07:18 UTC, piotr-grosicki requested changes

2020-09-17 07:18 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public Object getOrder(@RequestParam Long orderId){
sztuczne dane powinny byc reprezentacja dto sztucznie wypelniana danymi w controllerze

2020-09-18 10:50 UTC, piotr-grosicki approved these changes

2020-09-18 10:51 UTC, piotr-grosicki commented
Konflikty z masterem - do naprawienia :)

2020-09-19 07:48 UTC, piotr-grosicki requested changes
konflikty

2020-09-20 22:07 UTC, hubertb98 reviewed
Myślę, że udało mi się naprawić to o co chodzi.
Co do budowy katalogów w projekcie to reszta się zgodziła na taką budowę

2020-09-21 07:45 UTC, piotr-grosicki approved these changes

2020-09-21 07:45 UTC, merged