Entity Group-Product
piotr-grosicki/project-jdp-2009-01 pull request #20
Opened 2020-09-30 13:32 UTC by sobek21

2020-09-30 13:38 UTC, hubertb98 approved these changes

2020-09-30 15:59 UTC, draztel reviewed
Dobrze by było wszystkie nazwy kolumn napisać z wielkich liter

2020-09-30 17:54 UTC, hubertb98 requested changes

2020-09-30 17:54 UTC, hubertb98 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@Table(name = "GROUP")
Nazwy tabeli piszemy w liczbie mnogiej. W tym przypadku prawdopodobnie wyskoczy błąd z bazą danych.

2020-10-01 21:14 UTC, hubertb98 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@Table(name = "\"GROUPS\"")
Albo może po prostu PRODUCTS_GROUP?

2020-10-01 21:25 UTC, draztel approved these changes

2020-10-01 21:27 UTC, draztel commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@Table(name = "\"GROUPS\"")
mi pasują oba

2020-10-02 08:28 UTC, piotr-grosicki approved these changes

2020-10-02 08:29 UTC, merged