naprawa relacji Group 1 - N Product
piotr-grosicki/project-jdp-2009-01 pull request #22
Opened 2020-10-02 16:12 UTC by draztel

- zmodyfikowałem pola ID w obu klasach
- dopisałem  `= new ArrayList<>();` do listy products w klasie Group
- zrobiłem odstępy bo się czytać nie dało

2020-10-03 10:34 UTC, pablodlugi requested changes

2020-10-03 10:34 UTC, pablodlugi commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @GeneratedValue
Tutaj dodaj proszę `@GeneratedValue(strategy = GeneratedType.AUTO)`

2020-10-03 17:24 UTC, piotr-grosicki requested changes
konflikty

2020-10-03 18:08 UTC, Machikur commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @GeneratedValue
AUTO jest domyślną strategią, moim zdaniem nie ma potrzeby tego pisać

2020-10-03 18:41 UTC, pablodlugi commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @GeneratedValue
Jeżeli tak to ok.

2020-10-04 14:21 UTC, piotr-grosicki approved these changes

2020-10-04 14:21 UTC, merged