Task 20.0.0
piotr-grosicki/project-jdp-2009-01 pull request #23
Opened 2020-10-03 09:26 UTC by Machikur

- utworzyłem testy dla encji User a także testy relacji pomiędzy user, cart oraz order
-utworzyłem reposytorium orderDao na potrzeby testów
-drobne zmiany w klasach które mogły powodować błędy w testach

2020-10-03 10:14 UTC, pablodlugi requested changes
Testy wydają się dla mnie przeprowadzone dobrze, ale w klasie Cart przy polu User wydaje mi się, że cascade powinien być ustawiony na PERSIST. Inaczej testy encji Cart nie przechodzą. Ponadto brakuje testów na to czy cartId w tabeli User ma taka samą wartość jak w tabeli Cart (wystarczy dodać jedną asercję).

2020-10-03 14:46 UTC, Machikur commented
> Testy wydają się dla mnie przeprowadzone dobrze, ale w klasie Cart przy polu User wydaje mi się, że cascade powinien być ustawiony na PERSIST. Inaczej testy encji Cart nie przechodzą. Ponadto brakuje testów na to czy cartId w tabeli User ma taka samą wartość jak w tabeli Cart (wystarczy dodać jedną asercję).


-Nie jestem pewien czy PERSIST w tym przypadku jest pożądane. Myślę że User jest ścisle powiązany z Order oraz Cart i nie powinny być zachowane w przypadku usunięcia użytkownika więc Cascade.ALL wydaje sie dobrym rozwiązaniem
-co do testów to jasne, sprobuje dopisac taki test

2020-10-03 17:25 UTC, piotr-grosicki requested changes
konflikty

2020-10-03 18:40 UTC, pablodlugi commented
> > Testy wydają się dla mnie przeprowadzone dobrze, ale w klasie Cart przy polu User wydaje mi się, że cascade powinien być ustawiony na PERSIST. Inaczej testy encji Cart nie przechodzą. Ponadto brakuje testów na to czy cartId w tabeli User ma taka samą wartość jak w tabeli Cart (wystarczy dodać jedną asercję).
> 
> -Nie jestem pewien czy PERSIST w tym przypadku jest pożądane. Myślę że User jest ścisle powiązany z Order oraz Cart i nie powinny być zachowane w przypadku usunięcia użytkownika więc Cascade.ALL wydaje sie dobrym rozwiązaniem
> -co do testów to jasne, sprobuje dopisac taki test

Tak ale pole user w klasie Cart musi być PERSIST. Inaczej jak usuniesz cart to usuwa się również User, a tego nie chcemy

2020-10-03 19:16 UTC, Machikur commented
> > > Testy wydają się dla mnie przeprowadzone dobrze, ale w klasie Cart przy polu User wydaje mi się, że cascade powinien być ustawiony na PERSIST. Inaczej testy encji Cart nie przechodzą. Ponadto brakuje testów na to czy cartId w tabeli User ma taka samą wartość jak w tabeli Cart (wystarczy dodać jedną asercję).
> > 
> > 
> > -Nie jestem pewien czy PERSIST w tym przypadku jest pożądane. Myślę że User jest ścisle powiązany z Order oraz Cart i nie powinny być zachowane w przypadku usunięcia użytkownika więc Cascade.ALL wydaje sie dobrym rozwiązaniem
> > -co do testów to jasne, sprobuje dopisac taki test
> 
> Tak ale pole user w klasie Cart musi być PERSIST. Inaczej jak usuniesz cart to usuwa się również User, a tego nie chcemy

Zgadzam się, dziekuje za rade. Zastosuje to podejscie równierz w klasie order

2020-10-05 09:52 UTC, piotr-grosicki approved these changes

2020-10-05 09:52 UTC, merged