Jdp200901 25
piotr-grosicki/project-jdp-2009-01 pull request #25
Opened 2020-10-06 17:30 UTC by Machikur

-Rzeczywista implementacja UserController wraz z serwisem i mapperami
-mappery do encji cart oraz order stworzone na potrzeby implementacji zwracają puste dane
-Do utworzenia konta powinno wystarczyć nazwa użytkownika użytkownika oraz hasło
-pole key jest domyślnie nullem, generowane przez metodę createUserKey na czas jednej godziny po podaniu prawidłowych danych użytkownika

2020-10-06 21:04 UTC, pablodlugi approved these changes
Według mnie wszystko jest dobrze.

2020-10-06 21:14 UTC, hubertb98 approved these changes

2020-10-06 21:55 UTC, draztel approved these changes

2020-10-07 10:51 UTC, pablodlugi requested changes
Klasa 'UserDbService' można byłoby dodać wyjątki. Co wy na to?

2020-10-07 10:51 UTC, pablodlugi commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +}
Proponuję tutaj też rzucić wyjątkiem `UserNotFoundException`

2020-10-07 14:56 UTC, pablodlugi commented
> Klasa 'UserDbService' można byłoby dodać wyjątki. Co wy na to?
Przepraszam dopiero zuważyłem, że obsługujesz te wyjątki w momencie wywołania tych metod. Nie było tematu ;)

2020-10-07 14:57 UTC, pablodlugi commented
Przepraszam dopiero zuważyłem, że obsługujesz te wyjątki w momencie wywołania tych metod. Nie było tematu ;)

2020-10-07 14:57 UTC, pablodlugi approved these changes

2020-10-07 16:45 UTC, piotr-grosicki requested changes

2020-10-07 16:45 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +        Thread thread = new Thread(() ->
takie rozwiazanie jest bardzo nieoptymalne. wyobraz sobie system, ktory ma milion uzytkownikow, i dla kazdego z nich bedize odpalany nowy watek. 

Lepsze rozwiazania:
- scheduler odpalany co minute i pobierajacy aktywnych uzytkownikow i sprawdzajacy czy klucz powinien juz wygasnac (trzeba dodac do tabeli user timestamp utworzenia klucza)
- metoda i endpoint, ktora bedzie sprawdzala czy klucz wygasl czy nie (zamiast updatowac pole w klasie User mozna sprawdzac na biezaco czy taki klucz jest aktywny - wygladaloby to np tak: `user.getUserKey() != null && isUserKeyExpired(user.getUserKeyTimestamp)` i w tej metodzie `isUserKeyExpired` po prostu sprawdzasz czy timestamp byl zapisany powyzej godizny temu)

2020-10-07 19:41 UTC, Machikur commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +        Thread thread = new Thread(() ->
tez o tym myślalem. okej zrobie jak wyzej

2020-10-09 08:13 UTC, piotr-grosicki requested changes

2020-10-09 08:13 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private LocalDateTime keyTimeCreated=null;
sprawdzales czy ten mechanizm dziala? To pole nie jest nawet kolumna w bazie danych ;)

2020-10-09 18:03 UTC, Machikur commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private LocalDateTime keyTimeCreated=null;
poprawione

2020-10-11 12:13 UTC, piotr-grosicki requested changes
konflikt :)

2020-10-11 13:51 UTC, Machikur commented
> konflikt :)

naprawione

2020-10-12 07:43 UTC, piotr-grosicki approved these changes

2020-10-12 07:43 UTC, merged