Jdp200901 21 ProductController final implementation
piotr-grosicki/project-jdp-2009-01 pull request #27
Opened 2020-10-07 18:53 UTC by pablodlugi

- zaimplementowałem `ProductController`,
- dodałem klasy `ProductMapper`, `ProductNotFoundException`, `ProductConflictException` oraz `ProductDbService`,
- dodałem konnstruktor w encji `Product`.

2020-10-07 21:45 UTC, draztel approved these changes
wszystko raczej ok

2020-10-08 08:23 UTC, piotr-grosicki requested changes

2020-10-08 08:23 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        } catch (ProductConflictException pce) {
czemu ten wyjatek tutaj jest zjadany? uzytkownik nigdy nie dowie sie, ze cos jest nie tak

2020-10-08 08:23 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +            throw new ProductConflictException();
taka konstrukcja nie ma sensu, lapiemy wyjatek typu X, zeby zaraz rzucic wyjatek tego samego typu X

2020-10-08 08:23 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    public Product(Long productId, String productName, double productPrice, int quantity) {
jestes pewien, ze ten konstruktor nie powinien nic robic?

2020-10-08 10:42 UTC, pablodlugi commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    public Product(Long productId, String productName, double productPrice, int quantity) {
Zapomniałem uzupełnić. Faktycznie powinien być uzupełniony bo później wywoływany jest w klasie `ProductMapper`

2020-10-08 11:18 UTC, piotr-grosicki approved these changes

2020-10-08 11:19 UTC, merged