Blokowanie użytkowników - UserController
piotr-grosicki/project-jdp-2009-01 pull request #28
Opened 2020-10-08 10:15 UTC by pablodlugi

Spróbowałem rozwiązać problem z blokowaniem użytkowników po 1h. 
Mam nadzieję, że to jakoś wyszło. Wykorzystałem do tego `@Scheduled(fixedRate = 60000)` oraz dodałem `private Instant userKeyValidity;` do encji `User`.

2020-10-08 11:18 UTC, piotr-grosicki requested changes

2020-10-08 11:18 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +            if (user.getUserKeyValidity().equals(Instant.now())) {
troche za malo dokladne, rzadko kiedy zdazy sie zeby to zadzialalo. musialoby dokladnie co do ms sie zgadzac. Sugerowalbym sprawdzenie czy klucz nie jest starszy niz `Instant.now() - godzina` np

2020-10-08 18:47 UTC, Machikur commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +    public List<UserDto> mapToUserDtoList(final List<User> productList) {
nazwa listy troche mylna :P

2020-10-08 18:55 UTC, Machikur commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    @Scheduled(fixedRate = 60000)
być może się mylę, ale w tym wypadku wydaje mi się że ta metoda w kontrolerze jest zbędna. Wystarczy metoda w serwisie która by to aktualizowała bez dostępu użytkownika

2020-10-08 18:55 UTC, Machikur commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +                user.setEnable(false);
klucz nie powinien wpływać na blokadę konta. Przynajmniej nie takie było moje załozenie tworząc pole isEnable. Raczej chodziło o możliwość całkowitej blokady konta

2020-10-08 19:57 UTC, pablodlugi commented on src/main/java/com/kodilla/ecommercee/service/UserDbService.java
> +                user.setEnable(false);
Ok rozumiem wezmę to pod uwagę

2020-10-08 20:04 UTC, pablodlugi commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    @Scheduled(fixedRate = 60000)
chodzi Ci o metodę `blockUsers`? W tym przypadku metoda ta będzie się wykonywała co minutę, ale oprócz tego będzie można niezależnie od tego ją "uruchomić" za pomocą żądania, ale faktycznie można by było to schować w `DbService`. Może niech niech ktoś bardziej doświadczony od nas się wypowie co do tego :D

2020-10-08 20:05 UTC, pablodlugi commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +    public List<UserDto> mapToUserDtoList(final List<User> productList) {
za długo siedziałem nad `ProductController` ;P

2020-10-09 08:14 UTC, piotr-grosicki commented
Troche nie rozumiem sensu tego PR, chodzilo o pomoc koledze przy implementacji w tamtym PR a nie osobna swoja implementacje :)

2020-10-09 08:14 UTC, closed without merging