JDP200901-16 OrderEntityTest
piotr-grosicki/project-jdp-2009-01 pull request #31
Opened 2020-10-09 14:18 UTC by sobek21

2020-10-10 11:51 UTC, Machikur commented
dobrze by było sprawdzić zależność z User i Product przez jakąś asercje

2020-10-12 07:41 UTC, piotr-grosicki requested changes

2020-10-12 07:41 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/OrderEntityTest.java
> +    public void deleteById() {
brakuje sprawdzania czy podczas usuwania orderu w bazie zostaja produkty i uzytkownik

2020-10-12 07:49 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2020-10-12 20:49 UTC, draztel requested changes
w ostatnim tescie musisz osobno poustawiać obiekty dla każdej relacji np.
```
user.getOrders.add(order);
order.setUser(user);
order.getProducts.add(product);
product.setOrder(order);
```
jeśli się mylę to niech mnie ktos poprawi

2020-10-13 07:27 UTC, piotr-grosicki commented
> w ostatnim tescie musisz osobno poustawiać obiekty dla każdej relacji np.
> 
> ```
> user.getOrders.add(order);
> order.setUser(user);
> order.getProducts.add(product);
> product.setOrder(order);
> ```
> 
> jeśli się mylę to niech mnie ktos poprawi

nie powinno miec to znaczenia, kaskady dzialaja na tej zasadzie zeby wlasnie nie musiec podpinac obiektow z kazdej mozliwej strony. Podpinajac sie tylko w `Order` w bazie danych powstana odpowiednie klucze obce, ktore pozwola pozniej hibernatowi pobranie danych po kazdej stronie relacji

2020-10-13 07:27 UTC, merged