Jdp200901 1 product controller v1.1
piotr-grosicki/project-jdp-2009-01 pull request #5
Opened 2020-09-17 15:09 UTC by pablodlugi

- poprawiona implementacja endpointów w ProductController.
- przeniesienie wszystkich Controllerów do pakietu controller
- utworzenie pakietu dto.product i umieszczenie w nim nowej klasy ProductDto

2020-09-18 10:51 UTC, piotr-grosicki commented
Konflikty z masterem - do naprawienia :)

2020-09-18 15:50 UTC, pablodlugi commented
Konflikty naprawione

2020-09-19 07:47 UTC, piotr-grosicki requested changes

2020-09-19 07:47 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public void createProduct(@RequestBody Object object) {
tutaj powinno byc `ProductDto`

2020-09-19 07:47 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public Object updateProduct(@RequestBody ProductDto productDto) {
tutaj zwracane powinno byc `ProductDto`

2020-09-19 08:15 UTC, pablodlugi commented
Można mergować. Trochę się tutaj pogubiłem, ale mam nadzieję, że już wszystko gra.

2020-09-20 12:56 UTC, piotr-grosicki approved these changes

2020-09-20 12:57 UTC, merged