CartController wstepna implementacja
piotr-grosicki/project-jdp-2009-01 pull request #7
Opened 2020-09-18 12:59 UTC by sobek21

2020-09-18 13:52 UTC, piotr-grosicki commented
Konflikty z masterem :)

2020-09-19 07:49 UTC, piotr-grosicki requested changes

2020-09-19 07:49 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    //utworzenie pustego koszyka
komentarze do usuniecia, komentujemy tylko to co jest niejasne i jezeli juz to po angielsku :)

2020-09-19 07:49 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public CartDto getCart(Long cartId) {
brakuje `RequestParam`

2020-09-20 12:58 UTC, piotr-grosicki requested changes
Konflikty z masterem ;)

2020-09-20 12:58 UTC, piotr-grosicki requested changes
Konflikty z masterem ;)

2020-09-21 07:46 UTC, piotr-grosicki requested changes
konflikty ;)

2020-09-22 08:59 UTC, piotr-grosicki requested changes

2020-09-22 08:59 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    private CartDto cartDto;
beany w springu sa bezstanowe, nie moga przetrzymywac zadnych zmiennych w polach

2020-09-22 10:53 UTC, sobek21 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    private CartDto cartDto;
Mógłbyś trochę bardziej to wyjaśnić, nie rozumiem

2020-09-22 15:22 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    private CartDto cartDto;
w controllerze nie moze byc zadnych pol przetrzymujacych jakiekolwiek dane

2020-09-23 06:05 UTC, piotr-grosicki approved these changes

2020-09-23 06:05 UTC, merged